# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 561, 331))
        self.frame.setStyleSheet("background-color: rgb(153, 193, 241);\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_trainid = QtWidgets.QLabel(self.frame)
        self.label_trainid.setGeometry(QtCore.QRect(20, 9, 231, 51))
        self.label_trainid.setStyleSheet("QLabel{\n"
"    color: rgb(237, 51, 59);\n"
"    font: 24pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_trainid.setObjectName("label_trainid")
        self.label_from = QtWidgets.QLabel(self.frame)
        self.label_from.setGeometry(QtCore.QRect(45, 57, 171, 51))
        self.label_from.setStyleSheet("QLabel{\n"
"    \n"
"    font: 24pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_from.setObjectName("label_from")
        self.label_to = QtWidgets.QLabel(self.frame)
        self.label_to.setGeometry(QtCore.QRect(345, 61, 191, 41))
        self.label_to.setStyleSheet("QLabel{\n"
"    \n"
"    font: 24pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_to.setObjectName("label_to")
        self.label_time = QtWidgets.QLabel(self.frame)
        self.label_time.setGeometry(QtCore.QRect(20, 115, 311, 51))
        self.label_time.setStyleSheet("QLabel{\n"
"    font: 18pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_time.setObjectName("label_time")
        self.label_seatid = QtWidgets.QLabel(self.frame)
        self.label_seatid.setGeometry(QtCore.QRect(351, 115, 131, 51))
        self.label_seatid.setStyleSheet("QLabel{\n"
"    \n"
"    font: 18pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_seatid.setObjectName("label_seatid")
        self.label_warn_title = QtWidgets.QLabel(self.frame)
        self.label_warn_title.setGeometry(QtCore.QRect(18, 202, 151, 27))
        self.label_warn_title.setStyleSheet("QLabel{\n"
"    font: 16pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_warn_title.setObjectName("label_warn_title")
        self.label_warn = QtWidgets.QLabel(self.frame)
        self.label_warn.setGeometry(QtCore.QRect(14, 239, 391, 71))
        self.label_warn.setStyleSheet("QLabel{\n"
"    border: 2px dashed;\n"
"    font: 14pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_warn.setObjectName("label_warn")
        self.label_id = QtWidgets.QLabel(self.frame)
        self.label_id.setGeometry(QtCore.QRect(193, 207, 161, 21))
        self.label_id.setStyleSheet("QLabel{\n"
"    font: 18pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_id.setObjectName("label_id")
        self.Button_code = QtWidgets.QPushButton(self.frame)
        self.Button_code.setGeometry(QtCore.QRect(430, 212, 121, 111))
        self.Button_code.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255,0);\n"
"}")
        self.Button_code.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/ICONS/code.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_code.setIcon(icon)
        self.Button_code.setIconSize(QtCore.QSize(100, 100))
        self.Button_code.setObjectName("Button_code")
        self.Button_right_icon = QtWidgets.QPushButton(self.frame)
        self.Button_right_icon.setGeometry(QtCore.QRect(220, 59, 111, 51))
        self.Button_right_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/ICONS/exchange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_right_icon.setIcon(icon1)
        self.Button_right_icon.setIconSize(QtCore.QSize(60, 60))
        self.Button_right_icon.setObjectName("Button_right_icon")
        self.Button_close = QtWidgets.QPushButton(self.frame)
        self.Button_close.setGeometry(QtCore.QRect(246, 8, 311, 41))
        self.Button_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}")
        self.Button_close.setText("")
        self.Button_close.setIconSize(QtCore.QSize(20, 20))
        self.Button_close.setObjectName("Button_close")
        self.label_mi = QtWidgets.QLabel(self.frame)
        self.label_mi.setGeometry(QtCore.QRect(20, 165, 21, 27))
        self.label_mi.setObjectName("label_mi")
        self.label_price = QtWidgets.QLabel(self.frame)
        self.label_price.setGeometry(QtCore.QRect(42, 166, 85, 27))
        self.label_price.setStyleSheet("QLabel{\n"
"    font: 16pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_price.setObjectName("label_price")
        self.label_seat = QtWidgets.QLabel(self.frame)
        self.label_seat.setGeometry(QtCore.QRect(195, 167, 85, 27))
        self.label_seat.setStyleSheet("QLabel{\n"
"    font: 16pt \"Noto Sans Brahmi\";\n"
"}")
        self.label_seat.setObjectName("label_seat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Button_close.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_trainid.setText(_translate("MainWindow", "K775"))
        self.label_from.setText(_translate("MainWindow", "北 京 西 站"))
        self.label_to.setText(_translate("MainWindow", "上 海 虹 桥"))
        self.label_time.setText(_translate("MainWindow", "2024年08月05日 19:23开"))
        self.label_seatid.setText(_translate("MainWindow", "K775E04"))
        self.label_warn_title.setText(_translate("MainWindow", "仅供报销使用"))
        self.label_warn.setText(_translate("MainWindow", "                    报销凭证 遗失不补\n"
"                 退票改签时须交回车站"))
        self.label_id.setText(_translate("MainWindow", "43011280039"))
        self.label_mi.setText(_translate("MainWindow", "￥"))
        self.label_price.setText(_translate("MainWindow", "173.5"))
        self.label_seat.setText(_translate("MainWindow", "二 等 座"))
import svg_rc
