CREATE TRIGGER IF NOT EXISTS BUY_TICKET_SEAT1
AFTER INSERT ON RECORD
FOR EACH ROW
BEGIN
    UPDATE TRAIN SET SEAT1_NUM=SEAT1_NUM-1 WHERE TRAINID = NEW.TRAINID AND NEW.SEATLEVEL='一等座';
END;

CREATE TRIGGER IF NOT EXISTS BUY_TICKET_SEAT2
AFTER INSERT ON RECORD
FOR EACH ROW
BEGIN
    UPDATE TRAIN SET SEAT2_NUM=SEAT2_NUM-1 WHERE TRAINID = NEW.TRAINID AND NEW.SEATLEVEL='二等座';
END;

CREATE TRIGGER IF NOT EXISTS BUY_TICKET_SEAT3
AFTER INSERT ON RECORD
FOR EACH ROW
BEGIN
    UPDATE TRAIN SET SEAT3_NUM=SEAT3_NUM-1 WHERE TRAINID = NEW.TRAINID AND NEW.SEATLEVEL='无座';
END;