PRAGMA foreign_keys = ON;

-- 创建station(车站)表

CREATE TABLE IF NOT EXISTS STATION(
    STATIONNAME TEXT PRIMARY KEY NOT NULL,
    CITYNAME    TEXT NOT NULL
);

-- 创建passenger(乘客)表

CREATE TABLE IF NOT EXISTS PASSENGER(
    ID TEXT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    GENDER TEXT NOT NULL CHECK(GENDER IN('男','女')) DEFAULT '男',
    AGE INTEGER DEFAULT 1,
    TELEPHONE TEXT NOT NULL CHECK(LENGTH(TELEPHONE)=11),
    STATIONNAME TEXT,
    FOREIGN KEY (STATIONNAME) REFERENCES STATION(STATIONNAME) ON UPDATE CASCADE
);

-- 创建train(列车)表

CREATE TABLE IF NOT EXISTS TRAIN(
    TRAINID TEXT PRIMARY KEY NOT NULL,
    BEGINTIME TEXT NOT NULL,
    BEGINPLACE TEXT NOT NULL,
    ENDTIME TEXT NOT NULL,
    ENDPLACE TEXT NOT NULL,
    SEAT1_NUM INTEGER DEFAULT 80,
    SEAT1_PRICE REAL DEFAULT 40.0,
    SEAT2_NUM INTEGER DEFAULT 150,
    SEAT2_PRICE REAL DEFAULT 20.0,
    SEAT3_NUM INTEGER DEFAULT 100,
    SEAT3_PRICE REAL DEFAULT 20.0
);

-- 创建worker(管理员)表

CREATE TABLE IF NOT EXISTS WORKER(
    WORKID TEXT PRIMARY KEY NOT NULL,
    WORKAGE INTEGER DEFAULT 0
);

-- 创建pass(经过记录)关系表

CREATE TABLE IF NOT EXISTS PASS(
    TRAINID TEXT,
    STATIONNAME TEXT,
    FOREIGN KEY (TRAINID) REFERENCES TRAIN(TRAINID) ON UPDATE CASCADE,
    FOREIGN KEY (STATIONNAME) REFERENCES STATIONI(STATIONNAME) ON UPDATE CASCADE
);

-- 创建record(乘车记录)关系表

CREATE TABLE IF NOT EXISTS RECORD(
    ID TEXT,
    TRAINID TEXT,
    SEATID TEXT NOT NULL,
    SEATLEVEL TEXT NOT NULL CHECK(SEATLEVEL IN('一等座','二等座','无座')) DEFAULT '二等座',
    SEATPRICE REAL DEFAULT 0.0,
    FOREIGN KEY (ID) REFERENCES PASSENGER(ID) ON UPDATE CASCADE,
    FOREIGN KEY (TRAINID) REFERENCES TRAIN(TRAINID) ON UPDATE CASCADE
);

-- 创建regard(管理记录)关系表

CREATE TABLE IF NOT EXISTS REGARD(
    TRAINID TEXT,
    WORKID TEXT,
    WORKTIME TEXT NOT NULL,
    FOREIGN KEY (TRAINID) REFERENCES TRAIN(TRAINID) ON UPDATE CASCADE,
    FOREIGN KEY (WORKID) REFERENCES WORKER(WORKID) ON UPDATE CASCADE
);