-- 创建视图显示购买记录

CREATE VIEW IF NOT EXISTS RECORD_VIEW AS
SELECT T.TRAINID,T.BEGINTIME,T.BEGINPLACE,T.ENDTIME,T.ENDPLACE,
       R.SEATID,R.SEATLEVEL,R.SEATPRICE,R.ID
FROM TRAIN T
JOIN RECORD R ON T.TRAINID=R.TRAINID;


